name: Java CI with Maven Deploy to heroku

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_webapi:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11 ! :D
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Build with Maven Backend
      run: mvn -B package --file apisunat/pom.xml -DskipTests

    - name: Build, Push and Release a Docker container to Heroku Backend
      uses: gonuit/heroku-docker-deploy@v1.3.2
      with:

        email: ${{ secrets.HEROKU_EMAIL }}

        heroku_api_key: ${{ secrets.HEROKU_APY_KEY }}

        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

        dockerfile_directory: ./apisunat    #Lo habia dejado en demoapi u.u

        dockerfile_name: DockerFile

        docker_options: "--no-cache"

        process_type: web
#                           Para la segunda aplicación
#jobs:
#  build_webapi2:
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Checkout
#      uses: actions/checkout@v2
#
#    - name: Set up JDK 11 ! :D
#      uses: actions/setup-java@v2
#      with:
#        distribution: 'zulu'
#        java-version: '11'
#
#    - name: Build with Maven Backend
#      run: mvn -B package --file demoapi-facturacion/pom.xml -DskipTests
#
#    - name: Build, Push and Release a Docker container to Heroku Backend
#      uses: gonuit/heroku-docker-deploy@v1.3.2
#      with:
#
#        email: ${{ secrets.HEROKU_EMAIL }}
#
#        heroku_api_key: ${{ secrets.HEROKU_APY_KEY }}
#
#        heroku_app_name: ${{ secrets.HEROKU_APP_NAME2 }}   #Debe tener un appname diferente o se va a sobreesctibir
#
#        dockerfile_directory: ./demoapi-facturacion
#
#        dockerfile_name: DockerFile
#
#        docker_options: "--no-cache"
#
#        process_type: web